---

- hosts: all
  gather_facts: yes

  vars_files:
    - vars/common.yml
    # - vars/java.yml
    - vars/sql-vault.yml

  roles:
    - patrick-hill.common

    - role: geerlingguy.mysql
      become: yes
